### ISSUE TITLE
PyPi woes?

### ISSUE THREAD

**Issue by HarryLovesCode** [hyperledger-labs/nephos#120]
```
root@ubuntu:~# pip install nephos
Collecting nephos
  Could not find a version that satisfies the requirement nephos (from versions: )
No matching distribution found for nephos
```

I see it on PyPi, but for whatever reason cannot pull it on any of my computers.

**Comment by inzamam-iqbal** [comment]
@HarryLovesCode nephos require python 3.7+ It won't work with python2. So try pip3 install nephos

**Comment by HarryLovesCode** [comment]
@inzamam-iqbal Wow, thanks for the quick reply. This was my bad.

```bash
python3.7 -m pip install nephos
```

Worked just fine. Thanks!
