### ISSUE TITLE
Improve logging and error displaying 

### ISSUE THREAD

**Issue by nicolapaoli** [hyperledger-labs/nephos#27]
We should be able to use the native python logging module to provide useful logging of information, warnings and errors.

**Comment by inzamam-iqbal** [comment]
Are we going to replace the print statements we are using for logging with native logger or Are we doing both?

**Comment by nicolapaoli** [comment]
@alexvicegrab can you advise on this and python logging module? 

I guess part of this would be to improve the way we print log, like moving to "warnings" some of the logs that now are formatted as as "errors" (e.g. check pod / helm release status, check identities before creating them and so on) .

**Comment by nicolapaoli** [comment]
e.g.
```
╰─➤  ./nephos/deploy.py -f examples/dev/nephos_config.yaml -v peer                                                                                                   2 ↵
helm status cdb-peer1
Command failed with CalledProcessError:
Error: getting deployed release "cdb-peer1": release: "cdb-peer1" not found
```

that should be a warning. Same for pods when running `cert-auth` and `orderer` (and `fabric`) and `composer`.

Also, similar error to fix as "warning" is:
```
kubectl exec ca-hlf-ca-6b887f758f-94xc4 -n cas -- cat /var/hyperledger/fabric-ca/msp/signcerts/cert.pem
Command failed with CalledProcessError:
cat: /var/hyperledger/fabric-ca/msp/signcerts/cert.pem: No such file or directory
command terminated with exit code 1

kubectl exec ca-hlf-ca-6b887f758f-94xc4 -n cas -- bash -c 'fabric-ca-client enroll -d -u http://$CA_ADMIN:$CA_PASSWORD@$SERVICE_DNS:7054'
```

**Comment by alexvicegrab** [comment]
The core python `logging` module is the way to go, yes, @inzamam-iqbal. So we should replace all print statements with it, so we can modulate the verbosity in detail and have timestamps for everything. And yes, we should convert some of the "errors" we print to "warnings", as you suggest @nicolapaoli.

**Comment by inzamam-iqbal** [comment]
@alexvicegrab Shall I do the following,

- Change verbose option to --log and let the user set log level
- I will setup the logger in deploy module so no need to pass the verbose to every module
- Change print statements to relevant logs
- Change  pretty_print to return a formatted string insted of printing so that I can use that string to log

**Comment by dbandin** [comment]
I would like to add few points if you guys measure them useful. I think we should differentiate the logging from executable scripts to modules. Some cool features we may have are:
- Instantiating logging only on executable scripts with the parameters taken.
- Any Module/Class that is imported to be used as tool and/or helper, handle a Nephos exception class with it's own Nephos exceptions. Then we handle exceptions when we call this modules and we only use logger in the interactive program, not the libraries.
- We could add configuration to use always logger, to send strings to standard output and/or file, depending on the specific use-case, or only log.
- Allow setting up logging levels by argument if using CLI scripts.

**Comment by alexvicegrab** [comment]
Agree with @inzamam-iqbal regarding setting up logger and removing the `verbose` option from functions/modules, giving a much cleaner API to the functions.

Agree also to update the `pretty_print`, good points all.

Agree with @dbandin that:

1. we can add sensible defaults for logging, so we don't log by default when using Nephos as a library, unless explicitly setting an option or flag (although this is an advanced feature, and we should create a separate issue for this).
2. create our own NephosException class, which would be useful to handle exceptions intelligently, but again, it's a separate issue.
3. customise the logger to send logs to different locations (by default standard output, but provide options to do this to a file, or eventually to a Kafka cluster or Fluentd, etc.), again I'd put this in a separate issue, as already adding the logging is quite a big task.

**Comment by dbandin** [comment]
Just a small point found today, it may fall in this issue.

The method execute_until_success is sending "False" for show_command and show_errors to the execute mehtod if it's not the first pass. Will be nice to see, if there is an error, which one is it, and if it changes over time, I guess that moving to logger, will change this behaviour. But to have it in account.

https://github.com/hyperledger-labs/nephos/blob/master/nephos/helpers/misc.py#L51

**Comment by inzamam-iqbal** [comment]
@dbandin I too felt it but anyway i kept the behavior as it is. So shall I change it to always (not only the first time)?

**Comment by dbandin** [comment]
@inzamam-iqbal, I agree, I would change the logic until the logging module is implemented, but if it's implemented, the parameters for show output and show error would be redundant, they should be removed, and maybe only leaving the verbosity configuration for the initialization of the logging module.
Having the show_errors messages for logging.error and show_commands for logging.debug, the logic will get even simpler, just few lines.
