### ISSUE TITLE
README still references old repository

### ISSUE THREAD

**Issue by tkuhrt** [hyperledger-labs/nephos#7]
In the [Installation section](https://github.com/hyperledger-labs/nephos#git-repository) of the README, there is a reference to the `aidtechnology` organization. This should be changed to the `hyperledger-labs` organization. 

```
git clone https://github.com/aidtechnology/nephos.git
```

should be

```
git clone https://github.com/hyperledger-labs/nephos.git
```

**Comment by nicolapaoli** [comment]
Good point @tkuhrt, will fix now. Thank you!
